### ISSUE TITLE
its showing wrong data

### ISSUE THREAD

**Issue by Raman117** [aVadim483/fast-excel-templator#8]
![image](https://github.com/aVadim483/fast-excel-templator/assets/105584135/d47fbbe5-eee3-4dbf-9b80-a09e81532c11)
![image](https://github.com/aVadim483/fast-excel-templator/assets/105584135/fd982ad7-c3d8-4f22-989e-f52209e3c47d)

here in column H which is 3.2.1.6.d it is showing random number

in code i used 
        $cells = $sheet->readRows();
and then looped the $cell

meanwhile, laravel excel shows data
![image](https://github.com/aVadim483/fast-excel-templator/assets/105584135/03561eb8-79c2-40df-b45c-e88fc13e3223)

so there is nothing wrong with xlsx file

**Comment by aVadim483** [comment]
This cell is in date format and the library is trying to convert the cell's value to a timestamp. I'll think about how to solve this problem

**Comment by aVadim483** [comment]
fixed in fast-excel-reader v2.15.5

**Comment by Raman117** [comment]
FYI issue still exists in reader after update

**Comment by aVadim483** [comment]
> here in column H which is 3.2.1.6.d it is showing random number

the same error? or maybe a little different?

**Comment by Raman117** [comment]
i think the same i am still seeing 1716246121 about 4-5 of them
the rest from same column are loading fine

**Comment by Raman117** [comment]
Also qwestion
when i open xlsx it starts from 2nd sheet
how do i open it from sheet 1?

**Comment by lollita** [comment]
I confirm fix. Ty.
